### PR TITLE
Setup pre-commit for external use

### LINKED ISSUE #6: (feature request) pre-commit hook
Would it be possible to add a [pre-commit](https://pre-commit.com/) hook for this? [Link to documentation as to how to add new hooks](https://pre-commit.com/#new-hooks) if that helps…

Thank you!

### PR DESCRIPTION
**Pull request by MatthieuBizien**
Public setup based on https://github.com/dnephin/pre-commit-golang/

Fix #6 and #11 

This PR will only work when #31 is merged.

Suggestions:

1. Create a new release v0.4.0 after the merge of  #31 and this PR
1. Remove the `Pre-commit hook example` of the README.

- Add pre-commit for developing acton-validation itself
- Add publically available pre-commit hook

### CODE REVIEW

**Comment by mpalmer** [comment]
I'm not a huge fan of the `pre-commit` tool, and I won't be using it myself, making it likely that the `.pre-commit-config.yaml` you've provided will go stale over time.  As such, I don't think I can really in good conscience merge this PR.

From the look of it, it's possible to host the shell script and associated scaffolding in a separate repo, so if you'd like to maintain that yourself, I'd be happy for the `action-validator` README to refer to your repo under a `## pre-commit support` subheading in `# Usage`, or something along those lines.

**Comment by mpalmer** [comment]
Yep, that's a reasonable middle ground -- keep the `.pre-commit-hooks.yaml`, trim the README entry to just show the example to add to a user's own `.pre-commit-config.yaml`, and move the shell script into `bin/` (and remove the `.sh` extension), and it'll be pretty close to ready to go.

**Comment by MatthieuBizien** [comment]
@mpalmer It's done

**Review by mpalmer — APPROVED** [review]
Looks :100:.  I'll defer merging this until I make the next release, so that your multi-file PR is released.  That release will happen once #26 is landed.

**Pull request merged**
